name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows you to manually run it from the Actions tab

jobs:
  update-readme:
    name: Update README with latest Dev.to posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # CHANGE THIS: Use your exact Dev.to RSS feed
          feed_list: "https://dev.to/feed/navinkukreja"
          comment_tag_name: "BLOG-POST-LIST"
          max_post_count: 4
